name:                buffered-output
version:             0.1.0.0
github:              "schnecki/buffered-output"
license:             BSD3
author:              "Manuel Schneckenreither"
maintainer:          "manuel.schnecki@gmail.com"
copyright:           "2023 Manuel Schneckenreither"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/buffered-output#readme>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- auto-update

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  buffered-output-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - buffered-output
